# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2ed9bdee3614daa88b576b9fbce26a28cfe903e45953f9c18c5328f68ad51f775fb38fd4deb721d3b9bf67e411636808fccbeec36dad2051710be36763d0cb6

test:
  secret_key_base: a05c3de5a1c297a074d51a9eaa25b7a901f44208ce86b986c57ae463a9358980f6d8ef89bf97f76e2bc99648fa22d9da53b6a1a8cef16318e65cca69ec584338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
